### ISSUE TITLE
CRAN release plans?

### ISSUE THREAD

**Issue by petermeissner** [hrbrmstr/rep#1]
Hey, are there any plans to release this to CRAN?

**Comment by hrbrmstr** [comment]
Finished the crawl delay component and i just need to figure out if it's worth expanding the scope to expose some of the "URL" functions or not

**Comment by petermeissner** [comment]
Good. My plan for https://github.com/ropenscilabs/robotstxt/issues/19 would be to include `rep::can_fetch()` into `robotstxt::paths_allowed()` the moment (or next day / week) rep is on CRAN.

**Comment by hrbrmstr** [comment]
Looks like all the remote testing platforms at giving this the 👍 so I’ll initiate the submission process once kid ⚽️ Is done.

I also vectorized `can_fetch()`.

**Comment by petermeissner** [comment]
👍 🎉

**Comment by hrbrmstr** [comment]
Just following up. CRAN asked that I change the pkg name (I kinda expected that) so it's now `spiderbar`. Doing one last round of pre-CRAN flight checks before resubmitting.

**Comment by petermeissner** [comment]
That sounds "wunderbar".

**Comment by hrbrmstr** [comment]
hitting CRAN mirrors throughout the day.
